//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageOfLegendArt.Core.LanguageOfLegendArt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calender
    {
        public int CalenderId { get; set; }
        public string Match { get; set; }
        public string Score { get; set; }
        public System.DateTime Time { get; set; }
        public int Status { get; set; }
    }
}
