//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageOfLegendArt.Core.LanguageOfLegendArt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Champion
    {
        public int ChampionId { get; set; }
        public string Name { get; set; }
        public string ChampIcon { get; set; }
        public string ImgFullScreen { get; set; }
        public string Description { get; set; }
    }
}
