//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageOfLegendArt.Core.LanguageOfLegendArt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Roles = new HashSet<Role>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public int ParentId { get; set; }
        public int Role { get; set; }
        public int CategoryStatus { get; set; }
        public long NumberPostOfCategory { get; set; }
    
        public virtual Role Role1 { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
