//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageOfLegendArt.Core.LanguageOfLegendArt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Tags = new HashSet<Tag>();
        }
    
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Description { get; set; }
        public Nullable<int> PostStatus { get; set; }
        public int PostBy { get; set; }
        public Nullable<System.DateTime> PostTime { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<long> View { get; set; }
        public string UrlSlug { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
