//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageOfLegendArt.Core.LanguageOfLegendArt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Posts = new HashSet<Post>();
        }
    
        public int UserId { get; set; }
        public string Email { get; set; }
        public string NickName { get; set; }
        public string Passwords { get; set; }
        public int UserStatus { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public int Role { get; set; }
        public Nullable<System.DateTime> BandedTime { get; set; }
        public string BandReason { get; set; }
        public Nullable<int> BandedBy { get; set; }
        public Nullable<System.DateTime> LastedLogin { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
        public virtual Role Role1 { get; set; }
    }
}
