//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageOfLegendArt.Core.LanguageOfLegendArt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Posts = new HashSet<Post>();
            this.BannedUsers = new HashSet<BannedUser>();
            this.BannedUsers1 = new HashSet<BannedUser>();
            this.PageDefaults = new HashSet<PageDefault>();
        }
    
        public int UserId { get; set; }
        public string Email { get; set; }
        public string NickName { get; set; }
        public string Passwords { get; set; }
        public int UserStatus { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public int Role { get; set; }
        public Nullable<System.DateTime> BandedTime { get; set; }
        public string BandReason { get; set; }
        public Nullable<int> BandedBy { get; set; }
        public Nullable<System.DateTime> LastedLogin { get; set; }
        public string Avatar { get; set; }
        public string TypeMember { get; set; }
        public string Cognomen { get; set; }
        public string PhoneNumber { get; set; }
        public string FullName { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
        public virtual Role Role1 { get; set; }
        public virtual ICollection<BannedUser> BannedUsers { get; set; }
        public virtual ICollection<BannedUser> BannedUsers1 { get; set; }
        public virtual ICollection<PageDefault> PageDefaults { get; set; }
    }
}
